name: D&D Character Bot

on:
  schedule:
    # Her 6 saatte bir çalıştır (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  
  workflow_dispatch:  # Manuel çalıştırma için
  
  push:
    branches: [ main ]  # Test için

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Generate and Post Character
      env:
        IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
      run: |
        python character_generator.py
