name: D&D Character Bot

on:
  schedule:
    # Günde 3 kez çalıştır (09:00, 15:00, 21:00 UTC)
    # UTC+3 (Türkiye): 12:00, 18:00, 00:00
    - cron: '0 9,15,21 * * *'
  
  workflow_dispatch:  # Manuel çalıştırma için
  
  push:
    branches: [ main ]  # Test için

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Generate and Post Character
      env:
        ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
      run: |
        python character_generator_zapier.py
