name: Run DnD Character Bot

on:
  workflow_dispatch:  # Manuel tetikleme
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalıştırır (UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DnD Character Bot
        env:
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
        run: python bot.py
