name: Run DnD Character Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir (UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run DnD Character Bot
        env:
          IFTTT_EVENT_NAME: ${{ secrets.IFTTT_EVENT_NAME }}
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
        run: python bot.py
